/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2025-06-06 05:32:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import controller.Proceso;
import model.Cambio;
import model.Producto;

public final class pagDetalle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controller.Proceso");
    _jspx_imports_classes.add("model.Cambio");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("model.Producto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Detalle de articulo</title>\n");
      out.write("        <link href=\"css/adminlte.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"css/estilosAct.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

           Producto art = (Producto)request.getAttribute("dato");
           Cambio cm = new Proceso().obtener();
           double precio = art.getUnit()/1;
           DecimalFormat df = new DecimalFormat("#.00");
           String pr = df.format(precio);
        
      out.write("\n");
      out.write("    <center>\n");
      out.write("        <h2>Detalle del Artículo ");
      out.print(art.getNombre());
      out.write("</h2>\n");
      out.write("        <hr>\n");
      out.write("         <a href=\"pagLisArt.jsp\">Categorías</a>\n");
      out.write("         <br>\n");
      out.write("        <form action=\"controlProd\" name=\"fr\">\n");
      out.write("            <input type=\"hidden\" name=\"opc\" value=\"7\">\n");
      out.write("            <input type=\"hidden\" name=\"coda\" value=\"");
      out.print(art.getId());
      out.write("\">\n");
      out.write("        <table border=\"1\" cellspacing=\"15\" cellpadding=\"15\">\n");
      out.write("            <tr> <td rowspan=\"5\"><img src=\"FOTOS/");
      out.print(art.getId());
      out.write(".jpg\" width=\"200\" height=\"200\">\n");
      out.write("                 <td> Descripcion <td>");
      out.print(art.getNombre());
      out.write("\n");
      out.write("            <tr> <td> Precio Unitario <td>S/");
      out.print(art.getUnit());
      out.write("                $");
      out.print(pr);
      out.write("\n");
      out.write("            <tr> <td> Stock <td>");
      out.print(art.getStock());
      out.write("\n");
      out.write("            <tr> <td> Cantidad a Comprar <td> <input type=\"text\" name=\"cantidad\">\n");
      out.write("            <tr> <td colspan=\"2\"> <center><a href=\"#\" onclick=\"valida()\"><img src=\"images/btnCarrito.gif\"></a></center>\n");
      out.write("        </table>\n");
      out.write("        </form>\n");
      out.write("            <script>\n");
      out.write("            function valida(){\n");
      out.write("                sk=");
      out.print(art.getStock());
      out.write("\n");
      out.write("                can=Number(fr.cantidad.value)\n");
      out.write("                if(can>sk){\n");
      out.write("                    alert('Stock no disponible. Solo hay '+sk); return;\n");
      out.write("                } \n");
      out.write("                fr.submit();\n");
      out.write("            }\n");
      out.write("            </script>\n");
      out.write("    </center>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
